dist: xenial
sudo: required
language: python
python: 
    - '3.7'
git:
    depth: false
before_install:
    - curl -s -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.0.1-amd64.deb
    - sudo dpkg -i --force-confnew elasticsearch-7.0.1-amd64.deb
    - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
    - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
    - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
    - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
    - sudo systemctl start elasticsearch
install:
    - pip install codecov
    - pip install pipenv
    - pipenv sync
addons:
    sonarcloud:
        organization: kristian-thy50409
before_script:
    - 'sleep 10' # Ensure Elasticsearch is up and running
script:
    - python -m plateypus.models
    - python -m pytest --cov-branch --cov-report term-missing:skip-covered --cov-report xml --cov=plateypus
after_success:
    - codecov
    - sonar-scanner
