dist: xenial
sudo: required
language: python
python: 
    - '3.7'
services:
    - elasticsearch
before_install:
    - cat /etc/elasticsearch/jvm.options
    - cat /etc/elasticsearch/log4j2.properties
    - cat /etc/default/elasticsearch
    - cat /etc/init.d/elasticsearch
    - sudo systemctl stop elasticsearch &&
      curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.0.0-amd64.deb &&
      sudo dpkg -i --force-confnew elasticsearch-7.0.0-amd64.deb &&
      sudo systemctl restart elasticsearch
    - sudo systemctl status elasticsearch
    - cat /etc/elasticsearch/jvm.options
    - cat /etc/elasticsearch/log4j2.properties
    - cat /etc/default/elasticsearch
    - cat /etc/init.d/elasticsearch
install:
    - pip install codecov
    - pip install pipenv
    - pipenv sync
addons:
    sonarcloud:
        organization: kristian-thy50409
before_script:
    - 'sleep 10' # https://docs.travis-ci.com/user/database-setup/#elasticsearch
script:
    - python plateypus/models.py
    - python -m pytest --cov-branch --cov-report term-missing:skip-covered --cov-report xml --cov=plateypus
    - sonar-scanner
after_success:
    - codecov
