dist: trusty
sudo: required
language: python
python: 
    - '3.7'
install:
    - 'pip install pipenv'
    - 'pipenv sync' 
addons:
    sonarcloud:
        organization: 'kristian-thy50409'
script:
    - 'python -m pytest --cov-branch --cov-report term-missing:skip-covered --cov-report xml --cov=plateypus'
    - 'codecov'
    - 'sonar-scanner'
