dist: xenial
sudo: required
language: python
python: 
    - '3.7'
before_install:
    - sudo systemctl stop elasticsearch
    - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.0.1-amd64.deb &&
      sudo dpkg -i --force-confnew elasticsearch-7.0.1-amd64.deb
    - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
    - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
    - |
      sudo cat <<-EOF >> /etc/elasticsearch/jvm.options
        -XX:+DisableExplicitGC
        -Djdk.io.permissionsUseCanonicalPath=true
        -Dlog4j.skipJansi=true
        -server
      EOF
    - sudo cat /etc/elasticsearch/jvm.options
    - sudo systemctl start elasticsearch
install:
    - pip install codecov
    - pip install pipenv
    - pipenv sync
    - sudo systemctl status elasticsearch
    - curl -v http://localhost:9200
addons:
    sonarcloud:
        organization: kristian-thy50409
before_script:
    - 'sleep 10' # Ensure Elasticsearch is up and running
script:
    - python plateypus/models.py
    - python -m pytest --cov-branch --cov-report term-missing:skip-covered --cov-report xml --cov=plateypus
    - sonar-scanner
after_success:
    - codecov
